# Generated by Django 3.0.7 on 2020-06-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('employee_id', models.CharField(max_length=20)),
                ('Birthday', models.DateField()),
                ('Gender', models.CharField(max_length=6)),
                ('user_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
