# Generated by Django 3.0.7 on 2020-06-07 05:11

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_employeeinfo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeinfo',
            name='user_image',
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to=main.models.get_upload_path)),
                ('name_of_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.EmployeeInfo')),
            ],
        ),
    ]
