# Generated by Django 3.0.7 on 2020-06-21 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
